config/routes.rb
KilavusPlatform::Application.routes.draw do

  resources :courses do
    resources :videos
  end

  devise_for :users
  get "platform/index"

  root "platform#index"

  

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :videos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @course }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :instructor, :description, :units, :duration)
    end
end

app/controllers/platform_controller.rb
class PlatformController < ApplicationController
  layout "main"
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @video }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:vimeoid, :title, :description, :duration, :visualization)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/courses/_form.html.haml
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @course.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :instructor
    = f.text_field :instructor
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :units
    = f.text_area :units
  .field
    = f.label :duration
    = f.text_field :duration
  .actions
    = f.submit 'Save'

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 Listing courses

%table
  %tr
    %th Name
    %th Instructor
    %th Description
    %th Units
    %th Duration
    %th
    %th
    %th

  - @courses.each do |course|
    %tr
      %td= course.name
      %td= course.instructor
      %td= course.description
      %td= course.units
      %td= course.duration
      %td= link_to 'Show', course
      %td= link_to 'Edit', edit_course_path(course)
      %td= link_to 'Destroy', course, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @course.name
%p
  %b Instructor:
  = @course.instructor
%p
  %b Description:
  = @course.description
%p
  %b Units:
  = @course.units
%p
  %b Duration:
  = @course.duration

= link_to 'Edit', edit_course_path(@course)
\|
= link_to 'Back', courses_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KilavusPlatform
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "Optimized for legibility.", name: "description"}/
    %meta{content: "A. Besir Kurtulmus", name: "author"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    %link{href: "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", rel: "stylesheet"}/
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/layouts/main.html.haml
!!!
%html
  %head
    %title KilavusPlatform
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "Optimized for legibility.", name: "description"}/
    %meta{content: "A. Besir Kurtulmus", name: "author"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    %link{href: "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", rel: "stylesheet"}
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/partials/_footer.html.haml
.well
  .footer.row-fluid
    .span4.footer-item
      %h3 Course Types
      %hr/
      %ul
        %li Item #
        %li Item #
        %li Item #
        %li Item #
        %li Item #
    .span4.footer-item
      %h3 About Us
      %hr/
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra quis est eget iaculis. Aenean sit amet mattis diam. Mauris tincidunt facilisis sapien non convallis.
    .span4.footer-item
      %h3 Contact Us
      %hr/
      %img{src: "http://placehold.it/200x200&text=Contact Info"}/
  %hr/
  .row-fluid
    .span4
      %p Copyrighted © Kilavus 2013
    .span8
      %p
        %a{href: "#"} 404 Error page

app/views/partials/_header.html.haml
.masthead
  .row-fluid
    .span6
    .span6
      %p.pull-right.muted
        - if user_signed_in?
          = link_to('Profile', edit_user_registration_path)
          |
          = link_to('Logout', destroy_user_session_path, :method => :delete)
        - else
          = link_to('Sign Up', new_user_registration_path)
          |
          = link_to('Sign In', new_user_session_path)

  = render "partials/navbar"

app/views/partials/_navbar.html.haml
.navbar
  .navbar-inner
    .container
      %ul.nav
        %li.active
          %a{href:"/"}>Home
        %li#nav-math
          %a{href:"#"}>Mathematics
        %li#nav-science
          %a{href:"#"}>Science
        %li#nav-humanities
          %a{href:"#"}>Humanities
        %li#nav-programming
          %a{href:"#"}>Programming

app/views/platform/index.html.haml
= render "partials/header"
/ Jumbotron
.jumbotron.well
  #main-top.row-fluid
    %h1 Free Courses
    %p.lead We provide a free and accessible education for everyone. Our platform is free and will always be free.
  .ribbon
    .ribbon-stitches-top
    %strong.ribbon-content
      %h1 Watch hundreds of courses now
    .ribbon-stitches-bottom
  .row-fluid
    #main-list.span4
      %a{href: "#"}
        %p
          %img.img-polaroid{src: "http://placehold.it/250x100&text=Course 1"}/
        %h2 Super Dope Videos
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra quis est eget iaculis.
    .span4
      %a{href: "#"}
        %p
          %img.img-polaroid{src: "http://placehold.it/250x100&text=Course 2"}/
        %h2 High Tech Monkeys
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra quis est eget iaculis.
    .span4
      %a{href: "#"}
        %p
          %img.img-polaroid{src: "http://placehold.it/250x100&text=Course 3"}/
        %h2 Über Kewl Servers
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra quis est eget iaculis.
  %hr/
  .row-fluid
    .span12
      .span4
      .span4
        %a.btn.btn-large.btn-block.btn-success{href: "#"} Start learning today
      .span4
= render "partials/footer"

app/views/videos/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :vimeoid
    = f.text_field :vimeoid
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :duration
    = f.text_field :duration
  .field
    = f.label :visualization
    = f.text_area :visualization
  .actions
    = f.submit 'Save'

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th Vimeoid
    %th Title
    %th Description
    %th Duration
    %th Visualization
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td= video.vimeoid
      %td= video.title
      %td= video.description
      %td= video.duration
      %td= video.visualization
      %td= link_to 'Show', video
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Vimeoid:
  = @video.vimeoid
%p
  %b Title:
  = @video.title
%p
  %b Description:
  = @video.description
%p
  %b Duration:
  = @video.duration
%p
  %b Visualization:
  = @video.visualization

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path